### ISSUE TITLE
By changing default name of metric, histogram metrics stops getting published. 

### ISSUE THREAD

**Issue by hjain25** [micrometer-metrics/micrometer#2671]
In this case, you just need to change the filter as well:

```yaml
    distribution:
        percentiles-histogram:
          i_want_to_be_different: true
```

_Originally posted by @jkschneider in https://github.com/micrometer-metrics/micrometer/issues/531#issuecomment-378305230_
