### ISSUE TITLE
micrometer won't respect  spring.cloud.gcp.core.enabled: false

### ISSUE THREAD

**Issue by xmlking** [micrometer-metrics/micrometer#2870]
micrometer won't respect  `spring.cloud.gcp.core.enabled: false` we also need to provide `management.metrics.export.stackdriver.enabled: false` which is redundant.

Context:  I want to disable GCP features when  running server on local laptop. 

```
# disable GCP for local dev
spring.cloud.gcp.core.enabled: false
management.metrics.export.stackdriver.enabled: false
```

**Comment by checketts** [comment]
I don't understand why they should be linked. Isn't it possible for non GCP users to use stackdriver?

In your base `application.yml` you could link them yourself:

```yaml
# disable GCP for local dev
spring.cloud.gcp.core.enabled: false
management.metrics.export.stackdriver.enabled: ${spring.cloud.gcp.core.enabled:false}
```
