### ISSUE TITLE
not able to see to custom metric(micrometer) published on dynatrace (log enabled)

### ISSUE THREAD

**Issue by Krithikavv** [micrometer-metrics/micrometer#3067]
**Describe the bug**
im working on integrating micrometer with dynatrace for monitoring purpose.
I try to run spring boot app with spring boot actuator /config specific for Dynatrace integration on micrometer docs page. used the same configs.  Tried changing log level  but no luck to see custom metric. only the system metrics are exported from micrometer.

I see this , but metrics are not getting exported from app still. 
```
[Loaded com.dynatrace.metric.util.DynatraceMetricApiConstants from file:/home/anscdev2/AN.gANHanaTeam-2355/spring-boot-jars/lib/com.dynatrace.metric.util.dynatrace-metric-utils-java-1.1.0.jar]
2022-03-09 22:29:50.459  INFO 23143 --- [           main] i.m.dynatrace.v2.DynatraceExporterV2     : Exporting to endpoint https://apm.cf.us30.hana.ondemand.com/e/e584d4c6-69cf-459a-a685-2ad0673f5ff7/api/v2/metrics/ingest
[Loaded com.dynatrace.metric.util.MetricBuilderFactory from file:/home/anscdev2/AN.gANHanaTeam-2355/spring-boot-jars/lib/com.dynatrace.metric.util.dynatrace-metric-utils-java-1.1.0.jar]
[Loaded com.dynatrace.metric.util.MetricBuilderFactory$MetricBuilderFactoryBuilder from file:/home/anscdev2/AN.gANHanaTeam-2355/spring-boot-jars/lib/com.dynatrace.metric.util.dynatrace-metric-utils-java-1.1.0.jar]
[Loaded java.util.Collections$2 from /usr/j2sdk1.8.0_302_x86_64-an-tzdata2021a-ca/jre/lib/rt.jar]
```
config on spring boot app:
not able to see any logs or details from micrometer dyantrace . also publishing is not happening to dynatrace. 
searched for spring.integration.<meter name> as per standard spring docs support.
```yaml
spring:
  profiles: default
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 205MB
server:
#application context root url path, this should match webserver config which is derived from
#Tomcat.ApplicationContext from DD.xml + appflags.cfg ServletNames, this is default, can be
#overridden in application.properties
  servlet:
    contextPath: path
micro:
  server.contextPath: path
an:
  appName: app1
  loadANPermissions: true
#  jpa.eclipselink.logging.level: FINE
#  jpa.eclipselink.logging.level.sql: FINE
db:
  modelGroupName: scmMicro
queue:
  servers: localhost:9123
  consumers:
  ---
spring:
  profiles: dev
server:
  servlet:
    contextPath:
management:
  server:
    port:

---
management:
  endpoints:
    metrics:
      enabled:
        - true
    web:
      exposure:
        include:
          - health
          - metrics
          - dynatrace

---
logging.level.io.micrometer.dynatrace: DEBUG

---
management.metrics.export.dynatrace:
   # Required only if not using the OneAgent endpoint
   # For SaaS: https://{your-environment-id}.live.dynatrace.com/api/v2/metrics/ingest
   # For managed deployments: https://{your-domain}/e/{your-environment-id}/api/v2/metrics/ingest
   uri: <https://uri>/api/v2/metrics/ingest

   # should be read from a secure source
   api-token: XXXX

   # These properties can only be used with the v2 exporter.
   v2:
     # Sets a prefix that is prepended to each exported metric key.
     metric-key-prefix: dynatest2

     # If set to true and a local OneAgent or operator is running, retrieves metadata
     # and adds it as additional dimensions to all data points (default: true)
     enrich-with-dynatrace-metadata: true

     # Sets an arbitrary number of key-value pairs as default dimensions.
     # Micrometer tags will overwrite these dimensions, if they have the same key.
     # Each exported metric will contain these dimensions.
     default-dimensions:
       stack: "dev"

     # The export interval in which metrics are sent to Dynatrace (default: 60s).
     step: 30s
```
**Environment**
from server hosted : managed host machine. https://apm.cf.us30.hana.ondemand.com/e/e584d4c6-69cf-459a-a685-2ad0673f5ff7/ui/metrics?gtf=-2h&gf=all 
latest version : 1.8.3 (micrometer)
dyna micrometer registry : 1.8.3 
OS: linux
java: 1.8

java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)
**To Reproduce**
How to reproduce the bug:
expose any functionality API call from spring boot app to dynatrace with any metrics (timer,counter etc) 

**Expected behavior**
metrics should flow into dynatrace with name spring.integration.<meter name > as name

**Additional context**
Add any other context about the problem here, e.g. related issues.
