### ISSUE TITLE
The endpoint '/actuator/prometheus' is not exposed

### ISSUE THREAD

**Issue by christophe-f** [micrometer-metrics/micrometer#314]
Hi,

I just started a new project with Springboot 2M7 and micrometer 1.0.0-rc.5 and the endpoint '/actuator/prometheus' is not available by default.

It's not the same behaviour that I got with previous release. Not sure if it's a SB2 or micrometer bug.

Exposing the endpoint manually works fine:
```
management:
  endpoints:
    web:
      expose: ["/prometheus"]
```

Thanks,
Christophe
