### ISSUE TITLE
OTLP registry custom header support

### ISSUE THREAD

**Issue by stse** [micrometer-metrics/micrometer#3546]
**Please describe the feature request.**
Provide configuration properties to provide custom headers e.g. `API-Key` which are sent whenever metrics are posted to the OTLP endpoint.

Having something like this

```yaml
management:
  otlp:
    metrics:
      export:
        step: 1s
        url: https://otlp.eu01.nr-data.net/v1/metrics
        headers:
          API-Key: otlp-endpoint-api-key
```

so that these headers are sent with each request may be this way

```java
var builder = this.httpSender.post(this.config.url());
for (final var header : this.config.headers()) {
  builder = builder.withHeader(header.key(), header.value());
}
builder.withContent("application/x-protobuf", request.toByteArray()) .send();
```

see https://github.com/micrometer-metrics/micrometer/blob/029a887eb86476036d28527ebda890289161623a/implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpMeterRegistry.java#L108

Another solution would be to use the Open Telemetry SDK and allow to provide custom MetricExporter beans. This works very well already for tracing. Here I can provide custom SpanExporter beans.

**Rationale**
Having direct OTLP support is great but in order to connect with some OTLP endpoints, e.g. [NewRelics OTLP endpoints](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup/) a header containing an API key has to be sent with each request.
