### ISSUE TITLE
percentiles/quantile distribution conf does not work in otlp registry 1.11.0 but ok in 1.11.0-M1 

### ISSUE THREAD

**Issue by cboudereau** [micrometer-metrics/micrometer#3855]
micrometer otlp does not send quantile like in 1.11.0-M1. The prometheus registry is working fine though (so it is not a configuration issue)

```yaml
  metrics:
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0.5, 0.95, 0.99
```

**Environment**
 - Micrometer version : 1.11.0 (works correctly with 1.11.0-M1 and 1.10.7) / Spring 2.7.0
 - Micrometer registry : micrometer-registry-otlp
 - OS: windows
 - Java version: 17

**To Reproduce**
Setup distribution configuration
```yaml
metrics:
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0.5, 0.95, 0.99
```
Setup the otlp registry

The ```http_server_requests``` does not expose the ```quantile``` label but the ```le```

While it works with the prometheus registry (micrometer-registry-prometheus) but with the ```http_server_requests_seconds``` metric with the correct ```quantile``` label.

**Expected behavior**
```http_server_requests``` with the ```quantile``` but not the ```le``` label

**Comment by lenin-jaganathan** [comment]
This might work fine with some other registries like Prometheus because Prometheus exports client side percentiles and le bucketed histogram as individual meters as opposed to OTLP where these are exported as a single Data point (OTLP is just so efficient w.r.t wire protocol used to export the data)

**Comment by cboudereau** [comment]
Got it but the problem is that with the default configuration, the cardinality of ```le``` label is really high.

**Comment by lenin-jaganathan** [comment]
If you are worried using the le labelled buckets and instead want to generate only 50th, 95th and 99th percentile, you can go with below config.

```
metrics:
    distribution:
      percentiles:
        all: 0.5, 0.95, 0.99
```
