### ISSUE TITLE
Actuator prometheus endpoint spring  stopped working after upgrading to 1.13

### ISSUE THREAD

**Issue by rohan-changejar** [micrometer-metrics/micrometer#5103]
Actuator prometheus 

**Environment**
Production
Using this version https://mvnrepository.com/artifact/io.micrometer/micrometer-core/1.13.0
 - Micrometer version 1.13.
 - Micrometer registry prometheus 
 - OS: MacOs Sonoma
 - Java version: java 21.0.2 2024-01-16 LTS

How to reproduce the bug:
We upgraded the version of micrometer to 1.13 and this caused our actuator/prometheus endpoints to start failing. 
All other spring actuator endpoints continue to work, but this would throw an exception and fail.

**Expected behavior**
That this would continue to work as usual and metrics populated as expected

**Additional context**
Add any other context about the problem here, e.g. related issues.

**Comment by rohan-changejar** [comment]
> What version of Spring Boot are you using? Typically, if you're using Spring Boot, you should allow its dependency management to manage the versions of dependencies unless you have a reason to override it. I believe Spring Boot 3.3.0 (scheduled to be released next week) will manage Micrometer dependencies to version 1.13.0.

We are using this version of spring `    id 'org.springframework.boot' version '3.2.5'`, do you see any correlation of this issue with this version? 

If it is related, would propose adding this as a warning on the migration guide. 

Let me know if I could be of any help here

**Comment by joethehoff** [comment]
Same problem on my side using spring-boot 3.2.5
After upgrading to 1.13 there were no output at `localhost:9005/actuator/prometheus` anymore.
This are the management-props of application.properties
```
management:
  endpoint:
    health.enabled: true
    prometheus.enabled: true
  endpoints:
    enabled-by-default: false
    web.exposure.include: info, prometheus, health
  server:
    address: 0.0.0.0
    port: 9005
```
In sourecode we just use static Metrics-methods like this:
```
Metrics.counter("xxxx").increment();
```
