### ISSUE TITLE
After upgrading to version 1.13.0 endpoints are not exposed in Spring Boot with Prometheus

### ISSUE THREAD

**Issue by IlyaLisov** [micrometer-metrics/micrometer#5106]
**Describe the bug**
I was used `micrometer:1.12.6` in Spring Boot application, but yesterday upgraded to `1.13.0`. After that I get message on startup: `Exposing 0 endpoint(s) beneath base path '/actuator'`
I only changed version, but config stayed as it was.

**Environment**
 - Micrometer version: 1.13.0
 - Micrometer registry: prometheus
 - OS: macOS
 - Java version: 17

**To Reproduce**
My `application.yaml` file contains this config. I changed micrometer version from `1.12.6` to `1.13.0` and started to get 0 endpoints exposed
```
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    enable:
      request:
        enabled: true
      response:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
```

My `pom.xml` file contains:
```
<dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
<dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-registry-prometheus</artifactId>
        <scope>runtime</scope>
        <version>1.13.0</version>
</dependency>
```

**Expected behavior**
I expected that I don't need to change configs because of minor version was changed and there are no corresponding messages in release notes.
