### ISSUE TITLE
It is not possible to set a host-tag for Datadog

### ISSUE THREAD

**Issue by kuceram** [micrometer-metrics/micrometer#515]
Setting my Spring Boot 1.x application (actually Grails 3.x) properties of datadog metrics to:
```
management:
    metrics:
        export:
            datadog:
                enabled: true
                api-key: ***
                host-tag: myapp-dev
                steps: 1m
```
causes host not to be sent into datadog. I even found a [problematic code](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-datadog/src/main/java/io/micrometer/datadog/DatadogMeterRegistry.java#L245) which doesn't make sense at all to me.

Am I missing something or is there a bug?
