### ISSUE TITLE
Histogram in prometheus stop working if default name is changed

### ISSUE THREAD

**Issue by blacar** [micrometer-metrics/micrometer#531]
When using 

```
    web:
      server:
        requests-metric-name: i_want_to_be_different
```

in combination with

```
    distribution:
        percentiles-histogram:
          http:
            server:
              requests: true
```

It causes detailed histogram information stop showing in prometheus endpoint and only distribution metric is used.

It seems changing the default name causes micrometer to stop exporting the histogram details so there is something wrong with the requests-metric-name property.

This is tested using spring-boot 2 with actuator.

This is my entire config file:

```
management:
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
        percentiles-histogram:
          http:
            server:
              requests: true
  endpoints:
    web:
      exposure:
        include: prometheus,info,metrics,threaddump
```

**Comment by jkschneider** [comment]
In this case, you just need to change the filter as well:

```yaml
    distribution:
        percentiles-histogram:
          i_want_to_be_different: true
```
