### ISSUE TITLE
Value from environment variable `OTEL_EXPORTER_OTLP_ENDPOINT`  is not being used

### ISSUE THREAD

**Issue by mveitas** [micrometer-metrics/micrometer#5310]
**Describe the bug**
The value of the environment variable `OTEL_EXPORTER_OTLP_ENDPOINT` for our Kubernetes pod is not respected by Micrometer and the default value of `http://localhost:4318` is used.

Environment variables are supposed to take precedence over application properties as per the SpringBoot Externalized Configuration documentation: https://docs.spring.io/spring-boot/reference/features/external-config.html#page-title

The url has a default value of `http://localhost:4318/v1/metrics`
```
@ConfigurationProperties(
    prefix = "management.otlp.metrics.export"
)
public class OtlpProperties extends StepRegistryProperties {
    private String url = "http://localhost:4318/v1/metrics";
    private AggregationTemporality aggregationTemporality;
    private Map<String, String> resourceAttributes;
    private Map<String, String> headers;
    private TimeUnit baseTimeUnit;
```

Within a SpringBoot environment, this will never look to evaluate the environment variables as a url value is returned by default: https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpConfig.java#L52-L78

```
default String url() {
        return getUrlString(this, "url").orElseGet(() -> {
            Map<String, String> env = System.getenv();
            String endpoint = env.get("OTEL_EXPORTER_OTLP_METRICS_ENDPOINT");
            if (endpoint == null) {
                endpoint = env.get("OTEL_EXPORTER_OTLP_ENDPOINT");
            }
            if (endpoint == null) {
                endpoint = "http://localhost:4318/v1/metrics";
            }
            else if (!endpoint.endsWith("/v1/metrics")) {
                endpoint = endpoint + "/v1/metrics";
            }
            return endpoint;
        });
    }
```

From the app logs we see
`
overwatch-api-84b7495898-jv29m overwatch-api 2024-07-20T14:58:48.818Z  INFO 1 --- [overwatch-service] [           main] i.m.c.instrument.push.PushMeterRegistry  : Publishing metrics for OtlpMeterRegistry every 1m to http://localhost:4318/v1/metrics with resource attributes {k8s.container.name=overwatch-api, k8s.namespace.name=overwatch, k8s.node.name=xxxxx, k8s.pod.name=overwatch-api-84b7495898-jv29m, service.instance.id=overwatch.overwatch-api-84b7495898-jv29m.overwatch-api, service.version=1-058c220f-072024133821, service.name=overwatch-api, k8s.deployment.name=overwatch-api, k8s.replicaset.name=overwatch-api-84b7495898}
`

**Environment**
 - Micrometer version: 1.13.2
 - Micrometer registry: otlp
 - OS: linux
 - Java version: 17
 - SrpingBoot: 3.3.1

**To Reproduce**
How to reproduce the bug:

**Expected behavior**
The expected behavior is that the environment variables are respected and take precedence over the application properties

**Additional context**

We are using the OpenTelemetry auto-instrumentation to inject an agent into our SpringBoot application and automatically setting the `OTEL_EXPORTER_OTLP_ENDPOINT` environment variable. The auto-instrumentation via the opentelemetry-operator is injecting the following into the container at creation time:
```
java:
      env:
      - name: OTEL_METRICS_EXPORTER
        value: otlp
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://opentelemetry-collector.opentelemetry-collector.svc:4318
      image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.5.0
      resources:
        limits:
          cpu: 500m
          memory: 64Mi
        requests:
          cpu: 50m
          memory: 64Mi
```

Below is the output from our pod that shows the environment variable being set
```
containers:
    - env:
      - name: OTEL_NODE_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.hostIP
      - name: OTEL_POD_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      - name: OTEL_METRICS_EXPORTER
        value: otlp
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://opentelemetry-collector.opentelemetry-collector.svc:4318
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: JAVA_TOOL_OPTIONS
        value: ' -javaagent:/otel-auto-instrumentation-java/javaagent.jar'
      - name: OTEL_SERVICE_NAME
        value: overwatch-api
      - name: OTEL_RESOURCE_ATTRIBUTES_POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: OTEL_RESOURCE_ATTRIBUTES_NODE_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      - name: OTEL_PROPAGATORS
        value: tracecontext,baggage,b3
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: k8s.container.name=overwatch-api,k8s.deployment.name=overwatch-api,k8s.namespace.name=overwatch,k8s.node.name=$(OTEL_RESOURCE_ATTRIBUTES_NODE_NAME),k8s.pod.name=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME),k8s.replicaset.name=overwatch-api-7655949f67,service.instance.id=overwatch.$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME).overwatch-api,service.version=1-058c220f-072024133821
```
