### ISSUE TITLE
Missing metrics after update to 1.14.2 (spring boot 3.4.2)

### ISSUE THREAD

**Issue by Amunhateb** [micrometer-metrics/micrometer#5930]
Hello micrometer team.

We are experiencing a missing metrics after spring boot upgrade to 3.4 from 3.2. I have composed a sample app to demonstrate an issue.
This is it - https://github.com/Amunhateb/test-micrometer1
Related documentation - https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.actuator.management.metrics.distribution.percentiles

Metrics configuration:
```
management:
  metrics:
    distribution:
      percentiles:
        http:
          server:
            requests: 0.75, 0.95, 0.99
          client:
            requests: 0.75, 0.95, 0.99
      percentiles-histogram:
        http:
          server:
            requests: true
      slo:
        http:
          server:
            requests: 100ms,250ms,500ms,1s
```

If u set the parent to 3.2.12. U will see that app gives u these metrics:
`
http_server_requests_seconds{error="none",exception="none",method="GET",outcome="SUCCESS",service="test-micrometer1",status="200",uri="/metrics",quantile="0.75",} 0.318767104
http_server_requests_seconds{error="none",exception="none",method="GET",outcome="SUCCESS",service="test-micrometer1",status="200",uri="/metrics",quantile="0.95",} 0.318767104
http_server_requests_seconds{error="none",exception="none",method="GET",outcome="SUCCESS",service="test-micrometer1",status="200",uri="/metrics",quantile="0.99",} 0.318767104
`
If u set parent to 3.4.2 these metrics wont be available. Everything else besides these seems okay. Maybe it's a configuration migration issue but I cant find any info on that. Please help to understand what is going on here.

**Environment**
Spring boot 3.4.2, Micrometer 1.14.2.

**To Reproduce**
How to reproduce the bug:
Just switch parent version in pom.xml from 3.4.2 to 3.2.12 and see.

**Expected behavior**
Metrics in 1.14(SB 3.4) same as in 1.12(SB 3.2).
