### ISSUE TITLE
OTLP URL configuration does not comply with documentation

### ISSUE THREAD

**Issue by martinbeentjes** [micrometer-metrics/micrometer#6199]
**Describe the bug**
It seems that the configuration for the url of OTLP export is incorrectly implemented ór documented.

**Environment**

 - Micrometer version 1.14.3
 - Micrometer registry otlp
 - Java version: 17/21/23 

**To Reproduce**
How to reproduce the bug:

When configuring the open telemetry exporter endpoint through:

```yaml
management:
  metrics:
    tags:
      job: foobar-service
      env: ${ENVIRONMENT:prod}
  otlp:
    metrics:
      export:
        enabled: ${OTLP_EXPORT_METRICS:false}
        url: ${OPENTELEMETRY_COLLECTOR_ENDPOINT:}
```

We noticed that the metrics were not exported to Grafana Cloud via the otlp exporter. Previously we had configuration as:

```yaml
otlp:
  url: ${OPENTELEMETRY_COLLECTOR_ENDPOINT:}
```

After setting the environment variable `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT` the metrics were being exported again. If I then dive into the code of micrometer, I noticed that [`OtlpConfig::url()`](https://github.com/micrometer-metrics/micrometer/blob/815f0c4181d633f6ba36e11cd1b5c292c31473ed/implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpConfig.java#L62-L77) checks another property item, namely `otlp.url`, not `management.otlp.metrics.export.url`.

I expected that setting `management.otlp.metrics.export.url` would persist the URL into the OtlpConfig so that metrics would be exported.

I'd like to implement this fix, but was unable to get a start. I hope that my idea of what should happen is correct and this is actually buggy behavior.
