### ISSUE TITLE
Consider disabling Spring Boot Actuator metrics auto-configuration by default

### ISSUE THREAD

**Issue by izeye** [micrometer-metrics/micrometer#743]
Looking at [this SO question](https://stackoverflow.com/questions/50634144/merge-spring-boot-actuator-and-micrometer-data-on-one-endpoint) makes me think it's natural to disable Spring Boot Actuator metrics auto-configuration by default in Spring Boot 1.5.x support as Micrometer is intended to replace the legacy Spring Boot Actuator metrics support. Thoughts?

**Comment by mweirauch** [comment]
So something like this just programmatically (if possible):

```yml
endpoints:
  metrics:
    enabled: false
    filter:
      enabled: false

spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.actuate.autoconfigure.PublicMetricsAutoConfiguration
```
This is what I came up with a while ago. No idea if that `AutoConfiguration` is the only one required. As the "old" actuator metrics and `micrometer-spring-legacy` don't really collide, what would be the purpose of the feature? Less data gathering going on in the background is the only thing I can think off.
