### ISSUE TITLE
Hystrix latency percentile metrics

### ISSUE THREAD

**Issue by guxlightyear** [micrometer-metrics/micrometer#812]
I am currently developing a Spring Boot 2.0 application using Hystrix, and Prometheus for metrics.

I have noticed that the endpoint `/actuator/hystrix.stream` reports correctly a number of metrics, such as various latency percentiles [example hystrix-stream output attached](https://github.com/micrometer-metrics/micrometer/files/2332462/example-hystrix-stream-output.txt), but `/actuator/prometheus` does not contain those [example prometheus output attached](https://github.com/micrometer-metrics/micrometer/files/2332459/example-prometheus-output.txt)

I am under the impression that this commit https://github.com/micrometer-metrics/micrometer/commit/da19a7eceebf7cecddac035b74144b985db1bc17 (merged into master 2 weeks ago) will fix it.

Is that the case? If so, is it going to be included in Micrometer 1.0.7? and when will that be released?

For reference, and in case this problem is simply user error with my configuration, these are the software versions that I am currently using:
```
Spring Boot: 2.0.4.RELEASE
Micrometer: 1.0.6
Java: 1.8
Hystrix: 1.5.12
```

Relevant fragments from my build.gradle:
```
compile 'org.springframework.cloud:spring-cloud-starter-hystrix:1.4.5.RELEASE'
compile "org.springframework.boot:spring-boot-starter-actuator"
compile 'io.micrometer:micrometer-core'
compile 'io.micrometer:micrometer-registry-prometheus'
```

Relevant fragments from application.yml
```
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    hystrix:
      enabled: true
```

Thanks you,
Gustavo
